### ISSUE TITLE
havok.MotionType is undefined or Property 'MotionType' does not exist on type 'HavokPhysicsWithBindings'

### ISSUE THREAD

**Issue by junchih** [BabylonJS/havok#12]
A piece of code in typescript,

``` typescript
import * as havok from "@babylon/havok";

havok.MotionType.DYNAMIC; // runtime error, havok.MotionType is undefined

havok.default().then(
  (hk) => hk.MotionType.DYNAMIC // compiling time error, Property 'MotionType' does not exist on type 'HavokPhysicsWithBindings'
);
```

the issue is just above. And checked the source code, MotionType is defined in d.ts file as an enum, so why not const enum or put the definition in js file as well?

And do we have a gently solution for that?

Also, the compiling time error is nonsense, if the same code in javascript directly, it will work well.

**Comment by RaananW** [comment]
Trying to understand - are the types not defined in the right place (in the js code), or are they not exported at all? does it require a fix to the declaration file (i.e. setting the enums to be a member of the initialized module and not the top level) or to the js file (i.e. missing the type definition completely)?

**Comment by RaananW** [comment]
This should have been resolved by now. If it isn't, please reopen the issue.
