### ISSUE TITLE
`HP_World_GetNextTriggerEvent()` doesn't return `Result`

### ISSUE THREAD

**Issue by regnaio** [BabylonJS/havok#26]
In `HavokPhysics.d.t.s`:
```ts
/** Get the next collision event, following previousEvent. */
HP_World_GetNextCollisionEvent(world: number, previousEvent: number): number;

//...

/** Get the first trigger event generated by the previous world step. */
HP_World_GetNextTriggerEvent(world : HP_WorldId, previousEvent: number): [Result, number];
```

`HP_World_GetNextTriggerEvent()` appears to return `[Result, number]`, however, it actually only seems to return `number`.

Perhaps it is similar to `HP_World_GetNextCollisionEvent()`, which only returns `number`.

I'm curious if both `HP_World_GetNextTriggerEvent()` and `HP_World_GetNextCollisionEvent()` were meant to return a `Result` (or just a `number`)?

Thank you for your help! 🙂

**Comment by RaananW** [comment]
pinging @eoineoineoin

**Comment by eoineoineoin** [comment]
Thanks for spotting that!

> I'm curious if both HP_World_GetNextTriggerEvent() and HP_World_GetNextCollisionEvent() were meant to return a Result (or just a number)?

It's supposed to be just `number` - this would have originally started with returning a `Result`, but we dropped it in favour of just `number` after a performance pass.

**Comment by RaananW** [comment]
Does this require a change to the declaration file?
